# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/thejake/Documents/python/PyHC/mainForm.ui'
#
# Created: Mon Mar 19 22:08:53 2012
#      by: PyQt4 UI code generator 4.9
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1029, 776)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.w = QtGui.QWidget(MainWindow)
        self.w.setObjectName(_fromUtf8("w"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.w)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.wStack = QtGui.QStackedWidget(self.w)
        self.wStack.setObjectName(_fromUtf8("wStack"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.page)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 981, 706))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.widget_11 = QtGui.QWidget(self.horizontalLayoutWidget)
        self.widget_11.setMinimumSize(QtCore.QSize(250, 0))
        self.widget_11.setMaximumSize(QtCore.QSize(250, 16777215))
        self.widget_11.setObjectName(_fromUtf8("widget_11"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.widget_11)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.txtSearch = QtGui.QLineEdit(self.widget_11)
        self.txtSearch.setObjectName(_fromUtf8("txtSearch"))
        self.verticalLayout_6.addWidget(self.txtSearch)
        self.cmbSet = QtGui.QComboBox(self.widget_11)
        self.cmbSet.setObjectName(_fromUtf8("cmbSet"))
        self.verticalLayout_6.addWidget(self.cmbSet)
        self.lstFigures = QtGui.QListWidget(self.widget_11)
        self.lstFigures.setObjectName(_fromUtf8("lstFigures"))
        self.verticalLayout_6.addWidget(self.lstFigures)
        self.horizontalLayout_8.addWidget(self.widget_11)
        self.frame = QtGui.QFrame(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(350, 0))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.currentFigure = QtGui.QLabel(self.frame)
        self.currentFigure.setObjectName(_fromUtf8("currentFigure"))
        self.verticalLayout_5.addWidget(self.currentFigure)
        self.widget_12 = QtGui.QWidget(self.frame)
        self.widget_12.setObjectName(_fromUtf8("widget_12"))
        self.cmdAddToTeam = QtGui.QPushButton(self.widget_12)
        self.cmdAddToTeam.setGeometry(QtCore.QRect(0, 0, 114, 32))
        self.cmdAddToTeam.setObjectName(_fromUtf8("cmdAddToTeam"))
        self.verticalLayout_5.addWidget(self.widget_12)
        self.horizontalLayout_8.addWidget(self.frame)
        self.frame_2 = QtGui.QFrame(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout_8.addWidget(self.frame_2)
        self.wStack.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.page_2)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.m = QtGui.QHBoxLayout()
        self.m.setObjectName(_fromUtf8("m"))
        self.widget_5 = QtGui.QWidget(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setMinimumSize(QtCore.QSize(30, 0))
        self.widget_5.setMaximumSize(QtCore.QSize(30, 16777215))
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget_5)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.cmdLOF = QtGui.QPushButton(self.widget_5)
        self.cmdLOF.setCheckable(True)
        self.cmdLOF.setObjectName(_fromUtf8("cmdLOF"))
        self.verticalLayout_3.addWidget(self.cmdLOF)
        self.cmdObj = QtGui.QPushButton(self.widget_5)
        self.cmdObj.setCheckable(True)
        self.cmdObj.setObjectName(_fromUtf8("cmdObj"))
        self.verticalLayout_3.addWidget(self.cmdObj)
        self.cmdStandies = QtGui.QPushButton(self.widget_5)
        self.cmdStandies.setCheckable(True)
        self.cmdStandies.setObjectName(_fromUtf8("cmdStandies"))
        self.verticalLayout_3.addWidget(self.cmdStandies)
        self.cmdRemoveObject = QtGui.QPushButton(self.widget_5)
        self.cmdRemoveObject.setObjectName(_fromUtf8("cmdRemoveObject"))
        self.verticalLayout_3.addWidget(self.cmdRemoveObject)
        self.cmdBarrier = QtGui.QPushButton(self.widget_5)
        self.cmdBarrier.setCheckable(True)
        self.cmdBarrier.setObjectName(_fromUtf8("cmdBarrier"))
        self.verticalLayout_3.addWidget(self.cmdBarrier)
        self.cmdSmokeCloud = QtGui.QPushButton(self.widget_5)
        self.cmdSmokeCloud.setCheckable(True)
        self.cmdSmokeCloud.setObjectName(_fromUtf8("cmdSmokeCloud"))
        self.verticalLayout_3.addWidget(self.cmdSmokeCloud)
        self.cmdDebris = QtGui.QPushButton(self.widget_5)
        self.cmdDebris.setCheckable(True)
        self.cmdDebris.setObjectName(_fromUtf8("cmdDebris"))
        self.verticalLayout_3.addWidget(self.cmdDebris)
        self.cmdSpecial = QtGui.QPushButton(self.widget_5)
        self.cmdSpecial.setCheckable(True)
        self.cmdSpecial.setObjectName(_fromUtf8("cmdSpecial"))
        self.verticalLayout_3.addWidget(self.cmdSpecial)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.m.addWidget(self.widget_5)
        self.glFrame = QtGui.QGroupBox(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glFrame.sizePolicy().hasHeightForWidth())
        self.glFrame.setSizePolicy(sizePolicy)
        self.glFrame.setTitle(_fromUtf8(""))
        self.glFrame.setObjectName(_fromUtf8("glFrame"))
        self.verticalLayout = QtGui.QVBoxLayout(self.glFrame)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.vLayout = QtGui.QVBoxLayout()
        self.vLayout.setObjectName(_fromUtf8("vLayout"))
        self.verticalLayout.addLayout(self.vLayout)
        self.m.addWidget(self.glFrame)
        self.dialsContainer = QtGui.QGroupBox(self.page_2)
        self.dialsContainer.setMinimumSize(QtCore.QSize(192, 0))
        self.dialsContainer.setMaximumSize(QtCore.QSize(192, 16777215))
        self.dialsContainer.setTitle(_fromUtf8(""))
        self.dialsContainer.setObjectName(_fromUtf8("dialsContainer"))
        self.verticalLayoutWidget = QtGui.QWidget(self.dialsContainer)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 225, 671))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.dialsLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.dialsLayout.setMargin(0)
        self.dialsLayout.setObjectName(_fromUtf8("dialsLayout"))
        self.widget = QtGui.QWidget(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(200, 0))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.rollTwo = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rollTwo.sizePolicy().hasHeightForWidth())
        self.rollTwo.setSizePolicy(sizePolicy)
        self.rollTwo.setDefault(False)
        self.rollTwo.setFlat(False)
        self.rollTwo.setObjectName(_fromUtf8("rollTwo"))
        self.horizontalLayout.addWidget(self.rollTwo)
        self.rollOne = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rollOne.sizePolicy().hasHeightForWidth())
        self.rollOne.setSizePolicy(sizePolicy)
        self.rollOne.setDefault(False)
        self.rollOne.setFlat(False)
        self.rollOne.setObjectName(_fromUtf8("rollOne"))
        self.horizontalLayout.addWidget(self.rollOne)
        self.dialsLayout.addWidget(self.widget)
        self.widget_2 = QtGui.QWidget(self.verticalLayoutWidget)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 150))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.myDial = QtGui.QLabel(self.widget_2)
        self.myDial.setGeometry(QtCore.QRect(22, 0, 150, 150))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(150)
        sizePolicy.setHeightForWidth(self.myDial.sizePolicy().hasHeightForWidth())
        self.myDial.setSizePolicy(sizePolicy)
        self.myDial.setMinimumSize(QtCore.QSize(150, 150))
        self.myDial.setText(_fromUtf8(""))
        self.myDial.setObjectName(_fromUtf8("myDial"))
        self.dialsLayout.addWidget(self.widget_2)
        self.widget_4 = QtGui.QWidget(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setMinimumSize(QtCore.QSize(0, 30))
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.cmdHeal = QtGui.QPushButton(self.widget_4)
        self.cmdHeal.setObjectName(_fromUtf8("cmdHeal"))
        self.horizontalLayout_2.addWidget(self.cmdHeal)
        self.cmdTokenBlue = QtGui.QPushButton(self.widget_4)
        self.cmdTokenBlue.setObjectName(_fromUtf8("cmdTokenBlue"))
        self.horizontalLayout_2.addWidget(self.cmdTokenBlue)
        self.cmdTokenRed = QtGui.QPushButton(self.widget_4)
        self.cmdTokenRed.setObjectName(_fromUtf8("cmdTokenRed"))
        self.horizontalLayout_2.addWidget(self.cmdTokenRed)
        self.cmdDamage = QtGui.QPushButton(self.widget_4)
        self.cmdDamage.setObjectName(_fromUtf8("cmdDamage"))
        self.horizontalLayout_2.addWidget(self.cmdDamage)
        self.dialsLayout.addWidget(self.widget_4)
        self.gameLog = QtGui.QTextBrowser(self.verticalLayoutWidget)
        self.gameLog.setEnabled(True)
        self.gameLog.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.gameLog.setReadOnly(True)
        self.gameLog.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.gameLog.setOpenLinks(False)
        self.gameLog.setObjectName(_fromUtf8("gameLog"))
        self.dialsLayout.addWidget(self.gameLog)
        self.widget_3 = QtGui.QWidget(self.verticalLayoutWidget)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 150))
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.theirDial = QtGui.QLabel(self.widget_3)
        self.theirDial.setGeometry(QtCore.QRect(22, 0, 150, 150))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(150)
        sizePolicy.setHeightForWidth(self.theirDial.sizePolicy().hasHeightForWidth())
        self.theirDial.setSizePolicy(sizePolicy)
        self.theirDial.setMinimumSize(QtCore.QSize(0, 150))
        self.theirDial.setText(_fromUtf8(""))
        self.theirDial.setObjectName(_fromUtf8("theirDial"))
        self.dialsLayout.addWidget(self.widget_3)
        self.m.addWidget(self.dialsContainer)
        self.horizontalLayout_9.addLayout(self.m)
        self.wStack.addWidget(self.page_2)
        self.horizontalLayout_6.addWidget(self.wStack)
        MainWindow.setCentralWidget(self.w)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1029, 22))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menu_File = QtGui.QMenu(self.menuBar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menuView = QtGui.QMenu(self.menuBar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuGame = QtGui.QMenu(self.menuBar)
        self.menuGame.setObjectName(_fromUtf8("menuGame"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionChoose_Map = QtGui.QAction(MainWindow)
        self.actionChoose_Map.setObjectName(_fromUtf8("actionChoose_Map"))
        self.actionTeam_Builder = QtGui.QAction(MainWindow)
        self.actionTeam_Builder.setObjectName(_fromUtf8("actionTeam_Builder"))
        self.actionBattle_Map = QtGui.QAction(MainWindow)
        self.actionBattle_Map.setObjectName(_fromUtf8("actionBattle_Map"))
        self.menuView.addAction(self.actionTeam_Builder)
        self.menuView.addAction(self.actionBattle_Map)
        self.menuGame.addAction(self.actionChoose_Map)
        self.menuBar.addAction(self.menu_File.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuGame.menuAction())

        self.retranslateUi(MainWindow)
        self.wStack.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.currentFigure.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdAddToTeam.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdLOF.setText(QtGui.QApplication.translate("MainWindow", "L", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdObj.setText(QtGui.QApplication.translate("MainWindow", "O", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdStandies.setText(QtGui.QApplication.translate("MainWindow", "S", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdRemoveObject.setText(QtGui.QApplication.translate("MainWindow", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdBarrier.setText(QtGui.QApplication.translate("MainWindow", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdSmokeCloud.setText(QtGui.QApplication.translate("MainWindow", "Sm", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdDebris.setText(QtGui.QApplication.translate("MainWindow", "D", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdSpecial.setText(QtGui.QApplication.translate("MainWindow", "Sp", None, QtGui.QApplication.UnicodeUTF8))
        self.rollTwo.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.rollOne.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdHeal.setText(QtGui.QApplication.translate("MainWindow", "H", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdTokenBlue.setText(QtGui.QApplication.translate("MainWindow", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdTokenRed.setText(QtGui.QApplication.translate("MainWindow", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdDamage.setText(QtGui.QApplication.translate("MainWindow", "D", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuGame.setTitle(QtGui.QApplication.translate("MainWindow", "Game", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChoose_Map.setText(QtGui.QApplication.translate("MainWindow", "Change Map", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTeam_Builder.setText(QtGui.QApplication.translate("MainWindow", "Team Builder", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBattle_Map.setText(QtGui.QApplication.translate("MainWindow", "Battle Map", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

