# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/thejake/Documents/python/PyHC/mainForm.ui'
#
# Created: Wed Mar  7 01:16:06 2012
#      by: PyQt4 UI code generator 4.9
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(902, 700)
        self.w = QtGui.QWidget(MainWindow)
        self.w.setObjectName(_fromUtf8("w"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.w)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.m = QtGui.QHBoxLayout()
        self.m.setObjectName(_fromUtf8("m"))
        self.glFrame = QtGui.QGroupBox(self.w)
        self.glFrame.setTitle(_fromUtf8(""))
        self.glFrame.setObjectName(_fromUtf8("glFrame"))
        self.verticalLayout = QtGui.QVBoxLayout(self.glFrame)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.vLayout = QtGui.QVBoxLayout()
        self.vLayout.setObjectName(_fromUtf8("vLayout"))
        self.verticalLayout.addLayout(self.vLayout)
        self.m.addWidget(self.glFrame)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.m.addItem(spacerItem)
        self.dialsContainer = QtGui.QGroupBox(self.w)
        self.dialsContainer.setMaximumSize(QtCore.QSize(192, 16777215))
        self.dialsContainer.setTitle(_fromUtf8(""))
        self.dialsContainer.setObjectName(_fromUtf8("dialsContainer"))
        self.verticalLayoutWidget = QtGui.QWidget(self.dialsContainer)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 191, 671))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.dialsLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.dialsLayout.setMargin(0)
        self.dialsLayout.setObjectName(_fromUtf8("dialsLayout"))
        self.widget = QtGui.QWidget(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(200, 0))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.rollTwo = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rollTwo.sizePolicy().hasHeightForWidth())
        self.rollTwo.setSizePolicy(sizePolicy)
        self.rollTwo.setDefault(False)
        self.rollTwo.setFlat(False)
        self.rollTwo.setObjectName(_fromUtf8("rollTwo"))
        self.horizontalLayout.addWidget(self.rollTwo)
        self.rollOne = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rollOne.sizePolicy().hasHeightForWidth())
        self.rollOne.setSizePolicy(sizePolicy)
        self.rollOne.setDefault(False)
        self.rollOne.setFlat(False)
        self.rollOne.setObjectName(_fromUtf8("rollOne"))
        self.horizontalLayout.addWidget(self.rollOne)
        self.dialsLayout.addWidget(self.widget)
        self.widget_2 = QtGui.QWidget(self.verticalLayoutWidget)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 150))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.myDial = QtGui.QLabel(self.widget_2)
        self.myDial.setGeometry(QtCore.QRect(22, 0, 150, 150))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(150)
        sizePolicy.setHeightForWidth(self.myDial.sizePolicy().hasHeightForWidth())
        self.myDial.setSizePolicy(sizePolicy)
        self.myDial.setMinimumSize(QtCore.QSize(150, 150))
        self.myDial.setText(_fromUtf8(""))
        self.myDial.setObjectName(_fromUtf8("myDial"))
        self.dialsLayout.addWidget(self.widget_2)
        self.widget_4 = QtGui.QWidget(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setMinimumSize(QtCore.QSize(0, 30))
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.cmdHeal = QtGui.QPushButton(self.widget_4)
        self.cmdHeal.setObjectName(_fromUtf8("cmdHeal"))
        self.horizontalLayout_2.addWidget(self.cmdHeal)
        self.cmdTokenBlue = QtGui.QPushButton(self.widget_4)
        self.cmdTokenBlue.setObjectName(_fromUtf8("cmdTokenBlue"))
        self.horizontalLayout_2.addWidget(self.cmdTokenBlue)
        self.cmdTokenRed = QtGui.QPushButton(self.widget_4)
        self.cmdTokenRed.setObjectName(_fromUtf8("cmdTokenRed"))
        self.horizontalLayout_2.addWidget(self.cmdTokenRed)
        self.cmdDamage = QtGui.QPushButton(self.widget_4)
        self.cmdDamage.setObjectName(_fromUtf8("cmdDamage"))
        self.horizontalLayout_2.addWidget(self.cmdDamage)
        self.dialsLayout.addWidget(self.widget_4)
        self.gameLog = QtGui.QTextBrowser(self.verticalLayoutWidget)
        self.gameLog.setEnabled(True)
        self.gameLog.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.gameLog.setReadOnly(True)
        self.gameLog.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.gameLog.setOpenLinks(False)
        self.gameLog.setObjectName(_fromUtf8("gameLog"))
        self.dialsLayout.addWidget(self.gameLog)
        self.widget_3 = QtGui.QWidget(self.verticalLayoutWidget)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 150))
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.theirDial = QtGui.QLabel(self.widget_3)
        self.theirDial.setGeometry(QtCore.QRect(22, 0, 150, 150))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(150)
        sizePolicy.setHeightForWidth(self.theirDial.sizePolicy().hasHeightForWidth())
        self.theirDial.setSizePolicy(sizePolicy)
        self.theirDial.setMinimumSize(QtCore.QSize(0, 150))
        self.theirDial.setText(_fromUtf8(""))
        self.theirDial.setObjectName(_fromUtf8("theirDial"))
        self.dialsLayout.addWidget(self.widget_3)
        self.m.addWidget(self.dialsContainer)
        self.verticalLayout_2.addLayout(self.m)
        MainWindow.setCentralWidget(self.w)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.rollTwo.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.rollOne.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdHeal.setText(QtGui.QApplication.translate("MainWindow", "H", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdTokenBlue.setText(QtGui.QApplication.translate("MainWindow", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdTokenRed.setText(QtGui.QApplication.translate("MainWindow", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdDamage.setText(QtGui.QApplication.translate("MainWindow", "D", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

